app:
  name: "my-application"
  version: "1.0.0"
  environment: "development"
  debug: true

database:
  host: "localhost"
  port: 5432
  name: "myapp_dev"
  url: "postgresql://localhost:5432/myapp_dev"
  credentials:
    username: "admin"
    password: "${DB_PASSWORD}"

security:
  cors:
    origin: ["http://localhost:3000"]
    credentials: true
  headers:
    x-frame-options: "DENY"
    x-content-type-options: "nosniff"

logging:
  level: "debug"
  format: "json"
  output: "stdout"

api:
  token: "dev_token_12345678901234567890"
  rateLimit:
    windowMs: 900000
    max: 100
  timeout: 30000 