app:
  name: "my-application"
  version: "1.0.0"
  environment: "production"

database:
  host: "prod-db.example.com"
  port: 5432
  name: "myapp_prod"
  url: "postgresql://prod-db.example.com:5432/myapp_prod"
  credentials:
    username: "admin"
    password: "${DB_PASSWORD}"

security:
  cors:
    origin: ["https://myapp.com"]
    credentials: true
  headers:
    x-frame-options: "DENY"
    x-content-type-options: "nosniff"
    x-xss-protection: "1; mode=block"

logging:
  level: "info"
  format: "json"
  output: "stdout"

api:
  token: "prod_token_12345678901234567890"
  rateLimit:
    windowMs: 900000
    max: 50
  timeout: 30000

# Production-specific settings
monitoring:
  enabled: true
  metrics: true 