# SyntropyLog Staging Configuration
appName: "my-syntropylog-app"
environment: "staging"
logLevel: "info"

# Broker configuration
brokers:
  nats:
    enabled: true
    url: "nats://staging-nats:4222"

# Redis configuration
redis:
  enabled: true
  url: "redis://staging-redis:6379"

# HTTP configuration
http:
  enabled: true
  port: 3000

# Logging configuration
logging:
  transports:
    - type: "console"
      format: "json" 