# Development Environment Configuration - Perfect
app:
  name: "my-application"
  version: "1.0.0"
  environment: "development"

# Database Configuration - Perfect for Dev
database:
  host: "localhost"
  port: 5432
  name: "myapp_dev"
  credentials:
    username: "dev_user"
    password: "${DB_PASSWORD}"  # ✅ Using environment variable
    ssl: false  # ✅ Acceptable for local development
    sslMode: "prefer"

# Security Configuration - Perfect for Dev
security:
  cors:
    origin: ["http://localhost:3000", "http://localhost:3001"]
    credentials: true
    methods: ["GET", "POST", "PUT", "DELETE"]
    allowedHeaders: ["Content-Type", "Authorization"]
  
  headers:
    x-frame-options: "DENY"
    x-content-type-options: "nosniff"
    x-xss-protection: "1; mode=block"
    strict-transport-security: "max-age=31536000; includeSubDomains"
  
  authentication:
    jwt:
      secret: "${JWT_SECRET}"  # ✅ Using environment variable
      expiresIn: "24h"  # ✅ Longer for development convenience
      refreshExpiresIn: "7d"
      issuer: "myapp-dev"
      audience: "myapp-dev-users"
    
    bcrypt:
      rounds: 12
    
    rateLimit:
      windowMs: 900000
      max: 1000  # ✅ Higher limit for development
      message: "Too many requests from this IP"
  
  encryption:
    algorithm: "aes-256-gcm"
    key: "${ENCRYPTION_KEY}"  # ✅ Using environment variable

# Logging Configuration - Perfect for Dev
logging:
  level: "debug"  # ✅ Debug level for development
  format: "json"
  output: "stdout"  # ✅ Console output for development
  file:
    filename: "./logs/app.log"
    maxsize: "10MB"
    maxFiles: 5
    compress: true

# Monitoring Configuration - Perfect for Dev
monitoring:
  enabled: true
  metrics:
    enabled: true
    port: 9090
    path: "/metrics"
    auth: false  # ✅ No auth needed for local development
  
  health:
    enabled: true
    path: "/health"
    auth: false  # ✅ No auth needed for local development 