app:
  name: "my-application"
  version: "1.0.0"
  environment: "development"

database:
  host: "localhost"
  port: 5432
  name: "myapp"
  credentials:
    username: "admin"
    password: "${DB_PASSWORD}"  # ✅ Usando variable de entorno

security:
  cors:
    origin: ["https://myapp.com"]
    credentials: true
  headers:
    x-frame-options: "DENY"
    x-content-type-options: "nosniff"
    x-xss-protection: "1; mode=block"
    strict-transport-security: "max-age=31536000; includeSubDomains"

logging:
  level: "info"
  format: "json"
  output: "stdout"
  rotation:
    maxSize: "10MB"
    maxFiles: 5

cache:
  redis:
    host: "localhost"
    port: 6379
    password: "${REDIS_PASSWORD}"
    database: 0

api:
  rateLimit:
    windowMs: 900000
    max: 100
  timeout: 30000
  compression: true 