app:
  name: my-app
  environment: development
  port: 3000

database:
  host: localhost
  port: 5432
  name: dev_db

api:
  base_url: http://localhost:8000
  timeout: 5000
  retries: 3

logging:
  level: debug
  format: json
  output: console 