# Production YAML configuration file
database:
  host: db.production.com
  port: 5432
  name: myapp_prod
  ssl: true

api:
  host: 0.0.0.0
  port: 80
  timeout: 60
  debug: false

redis:
  host: redis.production.com
  port: 6379
  password: "secret_password"

logging:
  level: warn
  format: json
  output: file

# Production-specific settings
production:
  monitoring: true
  backup: true 