# Development YAML configuration file
database:
  host: localhost
  port: 5432
  name: myapp_dev
  ssl: false

api:
  host: 127.0.0.1
  port: 3000
  timeout: 30
  debug: true

redis:
  host: localhost
  port: 6379
  password: ""

logging:
  level: debug
  format: text
  output: console

# Development-specific settings
development:
  hot_reload: true
  mock_data: true 